language: csharp
solution: Ombi.sln
install:
 - mono Tools/nuget.exe restore Ombi.sln
 - nuget install NUnit.Runners -OutputDirectory testrunner  
script:
 - xbuild /p:Configuration=Release Ombi.sln /p:TargetFrameworkVersion="v4.5"
