version: 1.2.0
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '1.2.0'
  assembly_file_version: '1.2.{build}'
  assembly_informational_version: '1.2.0'
before_build:
- cmd: appveyor-retry nuget restore
build:
  verbosity: minimal
after_build:
- cmd: >-
    7z a PlexRequests.zip %APPVEYOR_BUILD_FOLDER%\PlexRequests.UI\bin\Release\

    appveyor PushArtifact PlexRequests.zip
