version: 2.2.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '2.2.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '2.2.0'


before_build:
- cmd: cd ombi/ombi
- appveyor-retry dotnet restore
- appveyor-retry npm install bower -g
- appveyor-retry npm install
- appveyor-retry bower install
build_script:
- dotnet build
after_build:
- dotnet publish -c Release -r win10-x64
- dotnet publish -c Release -r osx.10.12-x64
- dotnet publish -c Release -r ubuntu.16.10-x64
- dotnet publish -c Release -r debian.8-x64
- cmd: >-
    7z a Ombi_windows.zip %APPVEYOR_BUILD_FOLDER%\Ombi\Ombi\bin\Release\netcoreapp1.0\win10-x64\publish
    
    
    7z a Ombi_osx.zip %APPVEYOR_BUILD_FOLDER%\Ombi\Ombi\bin\Release\netcoreapp1.0\osx.10.12-x64\publish
    
    
    7z a Ombi_ubuntu.zip %APPVEYOR_BUILD_FOLDER%\Ombi\Ombi\bin\Release\netcoreapp1.0\ubuntu.16.10-x64\publish
    
    
    7z a Ombi_debian.zip %APPVEYOR_BUILD_FOLDER%\Ombi\Ombi\bin\Release\netcoreapp1.0\debian.8-x64\publish

    
    appveyor PushArtifact Ombi_windows.zip
    
    
    appveyor PushArtifact Ombi_osx.zip
    
    
    appveyor PushArtifact Ombi_ubuntu.zip
    
    
    appveyor PushArtifact Ombi_debian.zip
    
    

cache:
- '%USERPROFILE%\.nuget\packages'
deploy:
- provider: GitHub
  release: Ombi v$(appveyor_build_version)
  auth_token:
    secure: jDpp1/WUQl3uN41fNI3VeZoRZbDiDfs3GPQ1v+C5ZNE3cWdnUvuJfCCfUbYUV1Rp
  draft: true
  on:
    branch: master
