version: 3.0.{build}
configuration: Release
os: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '3.0.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '3.0.0'
before_build:
- ps: Update-NodeJsInstallation 7.8.0
- cmd: cd ombi/ombi
- node --version
- appveyor-retry dotnet restore
- appveyor-retry npm install bower -g
- appveyor-retry npm install -g gulp 
- appveyor-retry npm install
- appveyor-retry bower install
- gulp publish
build_script:
- dotnet build
after_build:
- dotnet publish -c Release -r win10-x64
- dotnet publish -c Release -r osx.10.12-x64
- dotnet publish -c Release -r ubuntu.16.10-x64
- dotnet publish -c Release -r debian.8-x64
- dotnet publish -c Release -r centos.7-x64
- cmd: >-
    7z a Ombi_windows.zip %APPVEYOR_BUILD_FOLDER%\Ombi\Ombi\bin\Release\netcoreapp1.1\win10-x64\publish
    
    
    7z a Ombi_osx.zip %APPVEYOR_BUILD_FOLDER%\Ombi\Ombi\bin\Release\netcoreapp1.1\osx.10.12-x64\publish
    
    
    7z a Ombi_ubuntu.zip %APPVEYOR_BUILD_FOLDER%\Ombi\Ombi\bin\Release\netcoreapp1.1\ubuntu.16.10-x64\publish
    
    
    7z a Ombi_debian.zip %APPVEYOR_BUILD_FOLDER%\Ombi\Ombi\bin\Release\netcoreapp1.1\debian.8-x64\publish
    
    
    7z a Ombi_centos.zip %APPVEYOR_BUILD_FOLDER%\Ombi\Ombi\bin\Release\netcoreapp1.1\centos.7-x64\publish

    
    appveyor PushArtifact Ombi_windows.zip
    
    
    appveyor PushArtifact Ombi_osx.zip
    
    
    appveyor PushArtifact Ombi_ubuntu.zip
    
    
    appveyor PushArtifact Ombi_debian.zip
    
    
    appveyor PushArtifact Ombi_centos.zip
    
    

cache:
- '%USERPROFILE%\.nuget\packages'
deploy:
- provider: GitHub
  release: Ombi v$(appveyor_build_version)
  auth_token:
    secure: jDpp1/WUQl3uN41fNI3VeZoRZbDiDfs3GPQ1v+C5ZNE3cWdnUvuJfCCfUbYUV1Rp
  draft: true
  on:
    branch: master
