version: 3.0.{build}
configuration: Release
os: Visual Studio 2017
environment:
  nodejs_version: "7.8.0"

install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
build_script:
  - ps: ./build.ps1
  
after_build:
- cmd: >-
    
    appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\src\Ombi\bin\Release\netcore1.1\windows.zip"
    
    
    appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\src\Ombi\bin\Release\netcore1.1\osx.tar.gz"
    
    
    appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\src\Ombi\bin\Release\netcore1.1\ubuntu.tar.gz"
    
    
    appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\src\Ombi\bin\Release\netcore1.1\debian.tar.gz"
    
    
    appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\src\Ombi\bin\Release\netcore1.1\centos.tar.gz"
    
    

#cache:
#- '%USERPROFILE%\.nuget\packages'
deploy:
- provider: GitHub
  release: Ombi v$(appveyor_build_version)
  auth_token:
    secure: jDpp1/WUQl3uN41fNI3VeZoRZbDiDfs3GPQ1v+C5ZNE3cWdnUvuJfCCfUbYUV1Rp
  draft: true
  on:
    branch: master

