version: 1.3.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '1.3.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '1.3.0'
before_build:
- cmd: appveyor-retry nuget restore
build:
  verbosity: minimal
after_build:
- cmd: >-
    7z a PlexRequests.zip %APPVEYOR_BUILD_FOLDER%\PlexRequests.UI\bin\Release\

    appveyor PushArtifact PlexRequests.zip
    
deploy:
- provider: GitHub
  release: PlexRequests $(appveyor_build_version)
  auth_token:
    secure: jDpp1/WUQl3uN41fNI3VeZoRZbDiDfs3GPQ1v+C5ZNE3cWdnUvuJfCCfUbYUV1Rp
  draft: true
  on:
    branch: master
