version: 2.2.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '2.2.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '2.2.0'


before_build:
- cmd: cd ombi/ombi
- cmd: dotnet restore
- cmd: appveyor-retry npm install
- cmd: dotnet publish -c Release -r win10-x64
- cmd: dotnet publish -c Release -r osx.10.12-x64
- cmd: dotnet publish -c Release -r ubuntu.16.10-x64
- cmd: dotnet publish -c Release -r debian.8-x64

build:
  verbosity: minimal
  project: Ombi.sln
after_build:
- cmd: >-
    7z a OmbiWidnows.zip %APPVEYOR_BUILD_FOLDER%\Ombi\Ombi\bin\Release\netcoreapp1.0\win10-x64\publish

    appveyor PushArtifact OmbiWindows.zip
    
deploy:
- provider: GitHub
  release: Ombi v$(appveyor_build_version)
  auth_token:
    secure: jDpp1/WUQl3uN41fNI3VeZoRZbDiDfs3GPQ1v+C5ZNE3cWdnUvuJfCCfUbYUV1Rp
  draft: true
  on:
    branch: master
